### ISSUE TITLE
[Feature / Vue] Dropping Vue-Resource

### ISSUE THREAD

**Issue by gisu** [kittn/generator-kittn#12]
Based on this Article https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.ehxb3xc23

We are dropping Vue-Resource and integrate Axios as HTTP Client Lib.

**Comment by CinKon** [comment]
https://github.com/kittn/generator-kittn/commit/5b31102af33a07ded84f2177164dee59bbf6b673
