### ISSUE TITLE
[Feature / Builder] Disable HMR

### ISSUE THREAD

**Issue by gisu** [kittn/generator-kittn#13]
If you create Pagetemplates without an MVC framework (React, Vue, Angular and similar), then HMR is rather disturbing. Then it might be a good idea to add HMR as an option. If you have the option with Vue (or React, Angular) deactivated.

**Comment by CinKon** [comment]
https://github.com/kittn/generator-kittn/commit/76f717ded7a450ea7b3c4d79bee685855ea3809e
