### ISSUE TITLE
CSS Filename is not set correctly in prototype mode

### ISSUE THREAD

**Issue by bastian-w** [kittn/generator-kittn#26]
The CSS filename is always style.css and not the value setted in the yeoman config process.

**Comment by gisu** [comment]
Tested five minutes ago, Prototype Mode 
![image](https://cloud.githubusercontent.com/assets/442468/22501736/6a2f2e70-e86a-11e6-98e8-c49d7385fed9.png)

**Comment by bastian-w** [comment]
its always style.css in the template file 

<img width="434" alt="bildschirmfoto 2017-02-01 um 12 26 19" src="https://cloud.githubusercontent.com/assets/4919392/22505051/ab413d68-e879-11e6-8dfc-5e745c93c5bc.png">
