### ISSUE TITLE
error Couldn't find match for "pull/6/head" for command-exists on npm install

### ISSUE THREAD

**Issue by mariarabelero** [kittn/generator-kittn#47]
On `npm install -g generator-kittn` I get:
`npm ERR! code 1
npm ERR! Command failed: /usr/bin/git checkout pull/6/head
npm ERR! error: pathspec 'pull/6/head' did not match any file(s) known to git.
npm ERR!
npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.rabelero.campos/.npm/_logs/2017-06-08T12_46_17_856Z-debug.log`

The error log shows this error message:
`35 silly fetchPackageMetaData error for command-exists@github:mathisonian/command-exists#pull/6/head Command failed: /usr/bin/git checkout pull/6/head
35 silly fetchPackageMetaData error: pathspec 'pull/6/head' did not match any file(s) known to git.
36 verbose stack Error: Command failed: /usr/bin/git checkout pull/6/head
36 verbose stack error: pathspec 'pull/6/head' did not match any file(s) known to git.
36 verbose stack
36 verbose stack     at ChildProcess.exithandler (child_process.js:252:12)
36 verbose stack     at emitTwo (events.js:125:13)
36 verbose stack     at ChildProcess.emit (events.js:213:7)
36 verbose stack     at maybeClose (internal/child_process.js:887:16)
36 verbose stack     at Socket.stream.socket.on (internal/child_process.js:340:11)
36 verbose stack     at emitOne (events.js:115:13)
36 verbose stack     at Socket.emit (events.js:210:7)
36 verbose stack     at Pipe._handle.close [as _onclose] (net.js:546:12)
37 verbose cwd /Users/m.rabelero.campos/Sites
38 verbose Darwin 15.6.0
39 verbose argv "/usr/local/Cellar/node/8.0.0_1/bin/node" "/usr/local/bin/npm" "install" "-g" "generator-kittn"
40 verbose node v8.0.0
41 verbose npm  v5.0.3
42 error code 1
43 error Command failed: /usr/bin/git checkout pull/6/head
43 error error: pathspec 'pull/6/head' did not match any file(s) known to git.
44 verbose exit [ 1, true ]`

On `yarn add generator-kittn` I get:
`yarn add v0.24.6
info No lockfile found.
[1/4] 🔍  Resolving packages...
error Couldn't find match for "pull/6/head" in "laggingreflex-sync,master,10/head,11/head,2/head,3/head,4/head,5/head,6/head,8/head,v0.1.0,v1.0.0,v1.0.1,v1.0.2,v1.1.0,v1.2.0,v1.2.1,v1.2.2" for "https://github.com/mathisonian/command-exists.git".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.`

**Comment by CinKon** [comment]
Will be fixed with next release!
Already fixed in develop-branch.

**Comment by CinKon** [comment]
https://github.com/kittn/generator-kittn/commit/cdeb5269f9af8fa5aa2df56766d3b4b14a4d9a9c
