### ISSUE TITLE
Starter Pack Craft Install Bugs

### ISSUE THREAD

**Issue by gisu** [kittn/generator-kittn#48]
Following the Bugs:

- Generator wont add a Database
- No .htaccess files in the `src/.system/` and `src/.system/en` folder (would be copied with `npm run init` task)
- Wrong filerights in `craftscripts`
- Smaller Webpack Error `GET http://localhost:3000/__webpack_hmr net::ERR_INCOMPLETE_CHUNKED_ENCODING`
- On Deploy CSS wont be minified

**Comment by CinKon** [comment]
Following the Bugs:

- [ ] Generator wont add a Database
- [ ] No .htaccess files in the src/.system/ and src/.system/en folder (would be copied with npm run init task)
- [ ] Wrong filerights in craftscripts
- [ ] Smaller Webpack Error GET http://localhost:3000/__webpack_hmr net::ERR_INCOMPLETE_CHUNKED_ENCODING
- [ ] On Deploy CSS wont be minified

**Comment by CinKon** [comment]
https://github.com/glenjamin/webpack-hot-middleware/issues/210
