### ISSUE TITLE
[Feature / Webpack] Option for Fully Featured Webpack Build

### ISSUE THREAD

**Issue by gisu** [kittn/generator-kittn#8]
Now i have included a Webpack Config with a Middleware for BrowserSync. Perfect for building Themes for a CMS.

But I think for the app development, it is better to use Webpack to the full extent. So as a bundler and a builder. Its also better for SSR with Vue.

## TODO
- Polish the actual Webpack Bundle Config
- Adding a second Option to use Webpack as Bundler and Builder

**Comment by CinKon** [comment]
Current Progress in `feature/webpackrewritten`

**Comment by CinKon** [comment]
Closed with #109
